name: Deploy to prod
# on:
#   workflow_dispatch:
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.2
    - name: Setting environment variables..
      run: |
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
        echo "AWS_SG_NAME=Surveyor_Security_Group" >> $GITHUB_ENV
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        
    - name: Deploy to prod server
      uses: appleboy/ssh-action@master
      with:
        host: 44.195.11.130
        username: ec2-user 
        key: ${{ secrets.SURVEYOR_GITHUB_SECRET }}
        script: |
          cd ~
          cd surveyor/
          git pull origin main 
          git status
          npm run compile

    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
      if: always()

####

#name: Deployment Workflow
#on:
#  push:
#    branches: [ main ]

#jobs:
#  job_one:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#    - name: testing surveyor server ssh connection
#      uses: appleboy/ssh-action@master
#      with:
#        host: 44.195.11.130
#        username: ec2-user
#        key: ${{ secrets.SURVEYOR_GITHUB_SECRET }}
#        port: 22
#        script: |
#          cd ~
#          cd surveyor/
#          git pull origin main 
#          git status
#          npm run compile
